#!/usr/bin/env perl

use warnings;
use strict;
use LWP::Simple qw/get/;
use WWW::Mechanize;
use Getopt::Long;
use Pod::Usage;
use constant {
	NAVER_DICTIONARY_URL => "http://endic.naver.com/search.nhn?isOnlyViewEE=N&query=", 
};
binmode(STDOUT, ":utf8");

our $VERSION = '0.01';

my %options;
GetOptions(\%options, "--help");

run(\%options, @ARGV);

sub run {
    my($opts, @words) = @_;

    if ($opts->{help}) {
        pod2usage(0);
    }

	if (@words == 0) {
		push @words, join '', <STDIN>;
	}

	for my $word (@words) {
		my @kor = get_naver($word);
		print join("\n", @kor), "\n";
	}
}

sub get_naver {
    my $word = shift;
	my $html = get(NAVER_DICTIONARY_URL . url_encode($word));
	my @kor = $html =~ m{<span class="fnt_k05">([^<].*?)</span>}sg;
	map { s/<[^>]*>//g } @kor;
	return @kor;
}

sub url_encode {
	my $url = shift;
	$url =~ s/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg;
	return $url;
}

sub url_decode {
	my $url = shift;
	$url =~ s/\%([A-Fa-f0-9]{2})/pack('C', hex($1))/seg;
	return $url;
}

__END__

=head1 NAME

eng2kor - English to Korean
Dictionary Service, it using naver dictionary

=head1 VERSION

Version 0.01

=head1 SYNOPSIS

	eng2kor "word"
	eng2kor some thing "something"
	echo "word" | eng2kor

=head1 INSTALL

	perl Makefile.PL
	make
	make install

=head1 AUTHOR

hshong, C<< <hshong at perl.kr> >>

=head1 LICENSE AND COPYRIGHT

Copyright 2010 hshong.

same as Perl.

=cut

1; # End of eng2kor
